# This rule is not used by the project hpp-pool-debug-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over debugger.test.local.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hpp-pool-debug-operator
    app.kubernetes.io/managed-by: kustomize
  name: debugger-admin-role
rules:
- apiGroups:
  - debugger.test.local
  resources:
  - debuggers
  verbs:
  - '*'
- apiGroups:
  - debugger.test.local
  resources:
  - debuggers/status
  verbs:
  - get
