# This rule is not used by the project hpp-pool-debug-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to debugger.test.local resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hpp-pool-debug-operator
    app.kubernetes.io/managed-by: kustomize
  name: debugger-viewer-role
rules:
- apiGroups:
  - debugger.test.local
  resources:
  - debuggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - debugger.test.local
  resources:
  - debuggers/status
  verbs:
  - get
